#=========================================================================
# Gamma make configuration
#=========================================================================

#=========================================================================
# Command-line options
# Modify for your system -or- use command-line argument OPTION=string
#=========================================================================
PLATFORM	= macosx
#PLATFORM	= linux
#PLATFORM	= windows

#USING_PUREDYNE = 1


BUILD_CONFIG	= release
#BUILD_CONFIG	= debug

STRICT_WARNINGS = 1

#=========================================================================
# Customize to fit your system
#=========================================================================
PREFIX     = /usr/local
CONFPREFIX = $(PREFIX)/etc
MANPREFIX  = $(PREFIX)/share/man

LIBS       =	-L$(PREFIX)/lib -L/usr/lib
CFLAGS     =	-I$(PREFIX)/include -I/usr/include \
		-Wall \
		-D__STDC_CONSTANT_MACROS
#		-fPIC \

LFLAGS     = $(LIBS) -lm -lstdc++
DLIBFLAGS := -Wl,-single_module

#-------------------------------------------------------------------------
# Default variables (may be overridden in platform specific section)
#-------------------------------------------------------------------------
AR		= ar cr
CC		= g++
INSTALL		= install
RANLIB		= ranlib
LIB_NAME	= gamma

BUILD_DIR	= build
SRC_DIR		= src
TEST_DIR	= tests
TUT_DIR		= tutorial

SLIB_EXT	= a
DLIB_EXT	= so
DLIB_OPT	= shared


#=========================================================================
# DO NOT EDIT BELOW!
#=========================================================================
#-------------------------------------------------------------------------
# Compilation flags
#-------------------------------------------------------------------------
INC_DIRS = ./ ./external/include

ifeq ($(BUILD_CONFIG), release)
	CFLAGS += -O3 -fpeel-loops
else
endif

ifneq ($(STRICT_WARNINGS), 0)
	CFLAGS += \
		-Wreturn-type -Wnon-virtual-dtor -Woverloaded-virtual \
		-Wformat -Wmissing-braces -Wparentheses -Wswitch \
		-Wunused-variable -Wsign-compare -Wno-unknown-pragmas
endif

#-------------------------------------------------------------------------
# Platform specific flags
#-------------------------------------------------------------------------
ifeq ($(PLATFORM), linux)

	ifdef USING_PUREDYNE
		CC      = gcc
		LFLAGS += /usr/lib/libportaudio.so.2 /usr/lib/libasound.so.2
	else
		LFLAGS += -lportaudio -lasound
	endif
	
	LFLAGS    += -lsndfile
	LFLAGS    += -lrt -lpthread
	CFLAGS    += -D__LINUX__
endif

ifeq ($(PLATFORM), macosx)
	LFLAGS    += -Lexternal/lib_osx
	LFLAGS    += -lsndfile -lportaudio
	LFLAGS    += -framework AudioUnit -framework AudioToolbox \
	             -framework CoreAudio -framework Carbon
#	CFLAGS	  += -isysroot /Developer/SDKs/MacOSX10.5.sdk -mmacosx-version-min=10.5
#	CFLAGS	  += -isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4
	CFLAGS	  += -isysroot /Developer/SDKs/MacOSX10.5.sdk -mmacosx-version-min=10.5 -arch i386
	DLIB_EXT   = dylib
	DLIB_OPT   = dynamiclib
endif

ifeq ($(PLATFORM), windows)
#	LFLAGS    += -Lexternal/lib_win32
#	LFLAGS    += ../external/lib_win32/libsndfile-1.lib ../external/lib_win32/portaudio_x86.lib
endif

#-------------------------------------------------------------------------
# Define dependent variables
#-------------------------------------------------------------------------
SLIB_FILE  = lib$(LIB_NAME).$(SLIB_EXT)
DLIB_FILE  = lib$(LIB_NAME).$(DLIB_EXT)
DLIBFLAGS := -$(SLIB_OPT) $(DLIBFLAGS)
#             -install_name @executable_path/$(DLIB_FILE)
BIN_DIR	= $(BUILD_DIR)/$(BUILD_CONFIG)
OBJ_DIR	= $(BIN_DIR)/obj

VPATH	= $(SRC_DIR)/ $(addprefix $(SRC_DIR)/, $(TEST_DIR) $(TUT_DIR))
